# Generated by Django 4.0.4 on 2022-04-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='upload_user_id',
            new_name='upload_user',
        ),
    ]
