# Generated by Django 4.0.4 on 2022-04-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_group_id_media_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='upload_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
