# Generated by Django 4.0.4 on 2022-04-23 13:59

import datetime
from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='create_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='media',
            name='upload_file',
            field=models.FileField(upload_to=media.models.upload_to_place),
        ),
    ]
