# Generated by Django 4.0.4 on 2022-04-23 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_media_create_time_alter_media_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='create_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(default='这个人很懒，什么都没有写', max_length=1000),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(default='这个人很懒，什么都没有写', max_length=200),
        ),
    ]
