# Generated by Django 4.0.4 on 2022-05-16 03:31

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('media', '0005_alter_media_create_time_alter_media_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
